version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_URL=http://localhost:8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=spa_docker
      - DB_USERNAME=spauser
      - DB_PASSWORD=spapassword

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=spa_docker
      - MYSQL_USER=spauser
      - MYSQL_PASSWORD=spapassword
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data: